### ISSUE TITLE
Feature Request: "Open Tile Manifest"

### ISSUE THREAD

**Issue by IngwiePhoenix** [felixkmh/ShortcutSync-for-Playnite#1]
Finally made it over to Github. Might make tracking stuff a little easier.

The tiles work super well and for, I'd guess, 99% of them, the default manifest works as expected. But a few of the icons I have used just don't play all to nice with having any text on the `150x150` style. So, I'd like to just open the respective XML with VSCode and edit it.

Would there be a way add an "Open Manifest" context menu entry? I can of course track the Playnite Entry ID and then go to that respective file. So this entry would simply be convenient to have. Hence why I am asking if it would be possible - or would it be more trouble than good?

ShortcutSync is defacto my most used extension.

Here are some screenshots where you can see where the text isn't very helpful:

Overall: 
![image](https://user-images.githubusercontent.com/2893716/102689441-6eb84200-41fe-11eb-90be-f990fc6b0e37.png)

"Final Fantasy" folder:
![image](https://user-images.githubusercontent.com/2893716/102689451-8394d580-41fe-11eb-95f6-0e8945f3f5a4.png)

**Comment by felixkmh** [comment]
I added the context menu entries to open the manifest and to directly toggle whether the text is shown on 150x150 tiles in release [v1.15.0](https://github.com/felixkmh/ShortcutSync-for-Playnite/releases/tag/v1.15.0).

**Comment by IngwiePhoenix** [comment]
That was incredibly fast O.O

Really love the "Toggle text on 150x150" option - even works on multi-select. That is super handy! Immediately went and cleaned up some of my icons with this. Thank you so much!
