### ISSUE TITLE
Why VBS?

### ISSUE THREAD

**Issue by AeliusSaionji** [felixkmh/ShortcutSync-for-Playnite#16]
Hello!

I just installed this addon, but I'm confused: why are we making shortcuts to a vbs that executes the playnite URI?

Shortcuts do support URIs- why the extra runaround step?

**Comment by felixkmh** [comment]
This is so that shortcuts pinned to the start menu in Windows 10 get custom tile images. I could not make that work without that extra indirection. Doesn't do much in Windows 11, but I didn't bother customizing that depending on the OS.
